// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package vectorstore

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigApiKey        = "api_key"
	DestinationConfigVectorStoreId = "vector_store_id"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigApiKey: {
			Default:     "",
			Description: "APIKey is the openai api key to use for the api client.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigVectorStoreId: {
			Default:     "",
			Description: "VectorStoreID is the id of the vector store to write records into.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
